### ISSUE TITLE
No output?

### ISSUE THREAD

**Issue by strarsis** [modularscale/modularscale-sass#150]
@scottkellum:
```scss
$modularscale: (
  base: 1em,
  ratio: $golden
);

article {
  @include ms-respond(padding, 6);
}
````

But there is no `padding` in `<article>`.
