### ISSUE TITLE
Can't make ms-respond to work

### ISSUE THREAD

**Issue by baglio** [modularscale/modularscale-sass#166]
I'm setting up a new project and I'd like to use the ms-respond mixin to have two breakpoint. The problem is that no matter how many breakpoints I put in the map, the mixin always returns the same value for each breakpoint:

## SCSS

```scss
$modularscale: (
    base: 12px,
    ratio: 1.333,

    640px: (
        base: 16px,
        ratio: 1.333,
    )
);

h1 {
    @include ms-respond(font-size, 3);
}
```

## CSS output

```css
h1 {
  font-size: 37.89749px; }
  @media (min-width: 640px) {
    h1 {
      font-size: 37.89749px; } }
```
