### ISSUE TITLE
Syntax for responsive

### ISSUE THREAD

**Issue by robsonsobral** [modularscale/modularscale-sass#178]
The `fluid()` function:

```scss
.foo {
	font-size: ms-fluid(1@320px, 3@480px);
}
```

Being the syntax:

```
ms-fluid(STEP@BREAKPOINT, STEP@BREAKPOINT)
```

**Question**: Is it possible to have infinite steps and breakpoints? Should we have them? Would that be useful?

We could get the value [using `clamp()`](https://css-tricks.com/linearly-scale-font-size-with-css-clamp-based-on-the-viewport/)

Even better, if we could have easing functions:

```scss
.bar {
	font-size: ms-fluid(1@320px, 3@480px, 'ease-in');
}
```

Being the default `"linear"`.

**Attention**: It have been really hard to find how to convert the Bézier cubic notations to mathematical functions.

**Comment by robsonsobral** [comment]
Should we infer steps from sizes?

```scss
.foobar {
	font-size: ms-fluid(16px@320px, 48px@480px);
}
```
